name: ai_experiment

dependencies:
  - python=3.8.20
  - pip=24.2
  - pip:
    - matplotlib==3.7.5
    - numpy==1.24.4
    - opencv_python==4.11.0.86
    - pillow==10.4.0
    - paddlepaddle_gpu==2.6.2.post120
    - -i https://pypi.tuna.tsinghua.edu.cn/simple
    - --extra-index-url=https://www.paddlepaddle.org.cn/packages/stable/cu120/

